version: "3.7"

services:
  backend:
    image: cloud-storage-diplom
    build: .
    container_name: cloud-storage
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=diploma
      - SPRING_DATASOURCE_PASSWORD=diploma
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_DATASOURCE_SCHEMA=public
      - SPRING_DATASOURCE_HIKARI_SCHEMA=public
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=public
      - SPRING_LIQUIBASE_ENABLED=true
    volumes:
      - ./logs:/logs
  db:
    image: 'postgres:12'
    container_name: db
    environment:
      - POSTGRES_USER=diploma
      - POSTGRES_PASSWORD=diploma